version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7

# tiny-trmnl
- package-ecosystem: "npm"
  directory: "/tiny-trmnl"
  schedule:
    interval: weekly
  cooldown:
    default-days: 7
