# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: tiny-TRMNL add-on
version: "0.0.3"
slug: tiny-trmnl
description: local TRMNL server for Home Assistant
url: "https://github.com/tenjaa/homeassistant-apps/tree/main/tiny-trmnl"
arch:
  - aarch64
init: false
ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: "tiny-TRMNL HTTP server"
map:
  - share:rw
options:
  home_assistant_token: null
  home_assistant_base_url: "http://homeassistant.local:8123"
  base_url: "http://localhost:8080"
  templates:
    - id: "family-calendar"
      plugin: "calendar"
      template: "calendar"
      config:
        calendars:
          - entity: calendar.my_calendar
            label: "A"
    - id: "weather-my-town"
      plugin: "weather"
      template: "weather"
      config:
        locationName: "Bamberg, Germany"
        latitude: 52.37052
        longitude: 9.73322
        timezone: "Europe/Berlin"
    - id: "daily-quote"
      plugin: "quote"
      template: "quote"
schema:
  home_assistant_token: "str"
  home_assistant_base_url: "str?"
  base_url: "str?"
  templates:
    - id: str
      plugin: str
      template: str
      config:
        calendars:
          - entity: "str?"
            label: "str?"
        locationName: "str?"
        latitude: "float?"
        longitude: "float?"
        timezone: "str?"
        title: "str?"
        quotes:
          - text: "str?"
            author: "str?"
image: "ghcr.io/tenjaa/tiny-trmnl-home-assistant"
